language: java
jdk:
    - openjdk8
install: cd src/web/WebContent && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
before_install:
addons:
    ssh_known_hosts: 175.24.94.79:22
after_success:
    - echo -e "$SSH_KEY_E" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh  -i ~/.ssh/id_rsa ubuntu@175.24.94.79 -p 22 "./setTomcat.sh"

