language: java
jdk:
- openjdk8
install: cd WebContent && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
before_install:
- openssl aes-256-cbc -K $encrypted_b4e472cb7874_key -iv $encrypted_b4e472cb7874_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
